import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import StoreProvider from "./providers/store-provider";
import ToastProvider from "./providers/toast-provider";
import Refresher from "@/components/refresher";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StoreProvider>
                <body className={cn("min-h-screen antialiased bg-[#E5E8EC]", manrope.className)}>
                    <Refresher>
                        <ToastProvider>
                            <Navbar />
                            {children}
                        </ToastProvider>
                    </Refresher>
                </body>
            </StoreProvider>
        </html>
    );
}
